### ISSUE TITLE
Ping Error in release mode

### ISSUE THREAD

**Issue by AashishChakravarty** [breakroom/sitemapper#10]
I am getting issue while deploying using docker with mix release mode.

It is working fine without docker.

```
* (MatchError) no match of right hand side value: {:error, :enoent}
    pubkey_os_cacerts.erl:38: :pubkey_os_cacerts.get/0
    httpc.erl:476: :httpc.ssl_verify_host_options/1
    httpc.erl:1015: anonymous fn/0 in :httpc.http_options_default/0
    httpc.erl:961: :httpc.http_options/3
    httpc.erl:771: :httpc.handle_request/9
    (elixir 1.15.5) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.15.5) lib/stream.ex:613: anonymous fn/4 in Stream.map/2
    nofile:1: (file)
```

**Comment by tomtaylor** [comment]
Going to close this as we're removing the ping function, because neither Google nor Bing support this any longer.
